//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bug_Tracker_Server.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class bug
    {
        public int bug_id { get; set; }
        public string bug_name { get; set; }
        public string bug_type { get; set; }
        public string bug_description { get; set; }
        public int bug_project_id { get; set; }
        public string bug_file { get; set; }
        public string bug_method { get; set; }
        public int bug_line { get; set; }
        public string bug_priority { get; set; }
        public string bug_severity { get; set; }
        public string bug_status { get; set; }
        public int bug_tester_id { get; set; }
        public Nullable<int> bug_developer_id { get; set; }
        public string bug_reject_reason { get; set; }
        public string bug_screenshot { get; set; }
        public System.DateTime bug_date { get; set; }
    
        public virtual user user { get; set; }
    }
}
