//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bug_Tracker_Server.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class project
    {
        public int project_id { get; set; }
        public string project_name { get; set; }
        public int project_manager_id { get; set; }
        public string project_status { get; set; }
    
        public virtual user user { get; set; }
    }
}
